@Api_HostAddress = https://localhost:7083

GET {{Api_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{Api_HostAddress}}/api/qotd

###

POST {{Api_HostAddress}}/api/authors
Content-Type: application/json

{
  //AuthorForCreateDto
}

###
